const express = require('express');
const { all, get, run } = require('../database/connection');
const router = express.Router();
const todayIso = () => new Date().toISOString().slice(0, 10);
const monthIso = () => new Date().toISOString().slice(0, 7);
const pct = (a,b) => b ? Math.round((a/b)*1000)/10 : 0;
const normalizePhone = (phone='') => { const d=String(phone).replace(/\D/g,''); return d ? (d.startsWith('55')?d:`55${d}`) : ''; };
const openStatuses = "status NOT IN ('Fechado','Perdido')";

function addDays(date, days) { const d = new Date(`${date}T00:00:00.000Z`); d.setUTCDate(d.getUTCDate() + days); return d.toISOString().slice(0, 10); }
function weekStartIso(date = new Date()) { const d = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate())); const day = d.getUTCDay() || 7; d.setUTCDate(d.getUTCDate() - day + 1); return d.toISOString().slice(0, 10); }
async function goalSummary() {
 const month = monthIso();
 const goal = await get('SELECT * FROM marketing_goals WHERE month = ? ORDER BY id DESC LIMIT 1',[month]) || await get('SELECT * FROM marketing_goals ORDER BY month DESC, id DESC LIMIT 1');
 const target = goal?.monthly_budget_target || 15;
 const row = await get(`SELECT COUNT(*) leads, SUM(CASE WHEN status IN ('Avaliação marcada','Compareceu','Orçamento enviado','Fechado') THEN 1 ELSE 0 END) evaluations, SUM(CASE WHEN status IN ('Orçamento enviado','Fechado') THEN 1 ELSE 0 END) budgets, SUM(CASE WHEN qualification='Qualificado' THEN 1 ELSE 0 END) qualified, SUM(CASE WHEN status IN ('Compareceu','Orçamento enviado','Fechado') THEN 1 ELSE 0 END) attended FROM lead_capture_entries WHERE substr(created_at,1,7)=?`,[month]);
 const day = Number(new Date().toISOString().slice(8,10)); const days = new Date(new Date().getUTCFullYear(), new Date().getUTCMonth()+1,0).getUTCDate();
 const expected = (target/days)*day; const budgets=row?.budgets||0;
 return { month, target, generated: budgets, missing: Math.max(target-budgets,0), daily_average_needed: Math.round((Math.max(target-budgets,0)/Math.max(days-day+1,1))*100)/100, leads_received: row?.leads||0, qualified_leads: row?.qualified||0, evaluations_scheduled: row?.evaluations||0, evaluations_done: row?.attended||0, attendance_rate: pct(row?.attended||0,row?.evaluations||0), budget_rate: pct(budgets,row?.leads||0), alert: budgets >= target ? 'acima da meta' : budgets >= expected ? 'dentro da meta' : 'abaixo da meta' };
}
async function buildWeeklyReport() {
 const start = weekStartIso(); const end = addDays(start, 6);
 const totals = await get(`SELECT COUNT(*) leads_week, SUM(CASE WHEN status IN ('Orçamento enviado','Fechado') THEN 1 ELSE 0 END) budgets_week FROM lead_capture_entries WHERE substr(created_at,1,10) BETWEEN ? AND ?`, [start, end]);
 const origins = await all(`SELECT COALESCE(origin,'Sem origem') label, COUNT(*) total FROM lead_capture_entries WHERE substr(created_at,1,10) BETWEEN ? AND ? GROUP BY COALESCE(origin,'Sem origem') ORDER BY total DESC, label ASC`, [start, end]);
 const campaigns = await all(`SELECT COALESCE(campaign,'Sem campanha') label, COUNT(*) leads, SUM(CASE WHEN status IN ('Orçamento enviado','Fechado') THEN 1 ELSE 0 END) budgets FROM lead_capture_entries WHERE substr(created_at,1,10) BETWEEN ? AND ? GROUP BY COALESCE(campaign,'Sem campanha') ORDER BY budgets DESC, leads DESC, label ASC`, [start, end]);
 const pending = await all(`SELECT title, due_date, channel FROM commercial_daily_tasks WHERE status!='Concluída' AND due_date<=? ORDER BY due_date ASC LIMIT 5`, [end]);
 const strong = campaigns.filter((c) => (c.budgets || 0) > 0 || c.leads >= 3).map((c) => `${c.label} (${c.leads} leads/${c.budgets || 0} orç.)`).join('; ') || 'Sem campanha forte nesta semana';
 const weak = campaigns.filter((c) => (c.budgets || 0) === 0).slice(0, 5).map((c) => `${c.label} (${c.leads} leads)`).join('; ') || 'Sem campanha fraca crítica';
 return { week_start: start, leads_week: totals?.leads_week || 0, budgets_week: totals?.budgets_week || 0, lead_origins: origins.map((o) => `${o.label}: ${o.total}`).join('; ') || 'Sem leads na semana', strong_campaigns: strong, weak_campaigns: weak, team_pending: pending.map((p) => `${p.channel} ${p.due_date}: ${p.title}`).join('; ') || 'Sem pendências vencidas', suggested_next_steps: 'Reforçar origens com maior retorno, ligar para atrasados e manter follow-up até orçamento enviado.' };
}
async function updateLeadStatus(id, status, extra = {}) {
 const next = extra.next_contact_date || (status === 'Contatado' ? addDays(todayIso(), 1) : null);
 await run(`UPDATE lead_capture_entries SET status=?, contacted=CASE WHEN ? IN ('Contatado','Avaliação marcada','Orçamento enviado','Fechado','Perdido') THEN 1 ELSE contacted END, qualification=CASE WHEN ? IN ('Avaliação marcada','Orçamento enviado','Fechado') THEN 'Qualificado' ELSE qualification END, next_contact_date=COALESCE(?, next_contact_date), last_interaction_at=CURRENT_TIMESTAMP, updated_at=CURRENT_TIMESTAMP WHERE id=?`, [status, status, status, next, id]);
 await run('INSERT INTO commercial_followup_actions (lead_id, action_type, channel, message, result, next_contact_date, status) VALUES (?,?,?,?,?,?,?)', [id, status, extra.channel || 'WhatsApp', extra.message || `Lead marcado como ${status}`, extra.result || status, next, 'Registrada']);
 return get('SELECT * FROM lead_capture_entries WHERE id=?', [id]);
}
router.get('/marketing-goals', async (req,res,next)=>{try{res.json({summary:await goalSummary(), goals: await all('SELECT * FROM marketing_goals ORDER BY month DESC')});}catch(e){next(e);}});
router.post('/marketing-goals', async (req,res,next)=>{try{const b=req.body; const r=await run('INSERT INTO marketing_goals (month, monthly_budget_target, notes) VALUES (?,?,?)',[b.month||monthIso(), b.monthly_budget_target||15, b.notes||'Meta mensal']); res.status(201).json(await get('SELECT * FROM marketing_goals WHERE id=?',[r.id]));}catch(e){next(e);}});
router.get('/flyers/campaigns', async(req,res,next)=>{try{res.json(await all('SELECT * FROM flyer_campaigns ORDER BY created_at DESC'));}catch(e){next(e);}});
router.post('/flyers/campaigns', async(req,res,next)=>{try{const b=req.body; const r=await run(`INSERT INTO flyer_campaigns (code,name,neighborhood,region,quantity_planned,responsible,cost,treatment,offer,whatsapp_message,qr_code_payload,short_link,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,[b.code,b.name,b.neighborhood,b.region,b.quantity_planned||0,b.responsible,b.cost||0,b.treatment,b.offer,b.whatsapp_message,b.qr_code_payload,b.short_link,b.status||'Ativa']); res.status(201).json(await get('SELECT * FROM flyer_campaigns WHERE id=?',[r.id]));}catch(e){next(e);}});
router.get('/flyers/distribution', async(req,res,next)=>{try{res.json(await all('SELECT d.*, c.code campaign_code FROM flyer_distribution d LEFT JOIN flyer_campaigns c ON c.id=d.campaign_id ORDER BY distribution_date DESC'));}catch(e){next(e);}});
router.post('/flyers/distribution', async(req,res,next)=>{try{const b=req.body; const r=await run('INSERT INTO flyer_distribution (campaign_id,neighborhood,region,street,quantity_distributed,distribution_date,responsible,cost,notes) VALUES (?,?,?,?,?,?,?,?,?)',[b.campaign_id,b.neighborhood,b.region,b.street,b.quantity_distributed||0,b.distribution_date||todayIso(),b.responsible,b.cost||0,b.notes]); res.status(201).json(await get('SELECT * FROM flyer_distribution WHERE id=?',[r.id]));}catch(e){next(e);}});
router.get('/lead-capture', async(req,res,next)=>{try{res.json(await all('SELECT * FROM lead_capture_entries ORDER BY created_at DESC'));}catch(e){next(e);}});
router.post('/lead-capture', async(req,res,next)=>{try{const b=req.body; const msg=`Olá, ${b.name}! Aqui é da BELLEART. Vi seu interesse em ${b.interest||'atendimento odontológico'}. Podemos agendar sua avaliação?`; const r=await run(`INSERT INTO lead_capture_entries (name,phone_whatsapp,interest,origin,campaign,neighborhood,notes,urgency,best_contact_time,status,qualification,suggested_whatsapp_message,next_contact_date) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,[b.name,b.phone_whatsapp,b.interest,b.origin,b.campaign,b.neighborhood,b.notes,b.urgency,b.best_contact_time,'Novo lead','Qualificar',msg,todayIso()]); await run(`INSERT INTO crm_contacts (name,phone,phone_whatsapp,source,interest,pipeline_stage,status,temperature,notes,next_contact_date) VALUES (?,?,?,?,?,?,?,?,?,?)`,[b.name,b.phone_whatsapp,b.phone_whatsapp,b.origin,b.interest,'Novo lead','Novo lead',b.urgency==='Alta'?'Quente':'Morno',b.notes,todayIso()]); await run(`INSERT INTO commercial_daily_tasks (lead_id,title,channel,due_date,status,priority,message) VALUES (?,?,?,?,?,?,?)`,[r.id,`Contato inicial: ${b.name}`,'WhatsApp',todayIso(),'Pendente','Alta',msg]); res.status(201).json({lead: await get('SELECT * FROM lead_capture_entries WHERE id=?',[r.id]), whatsapp_url:`https://wa.me/${normalizePhone(b.phone_whatsapp)}?text=${encodeURIComponent(msg)}`});}catch(e){next(e);}});
router.get('/commercial-routine/today', async(req,res,next)=>{try{const today=todayIso(); res.json({today, call_today: await all("SELECT * FROM commercial_daily_tasks WHERE due_date<=? AND channel='Telefone' AND status!='Concluída'",[today]), whatsapp_today: await all("SELECT * FROM commercial_daily_tasks WHERE due_date<=? AND channel='WhatsApp' AND status!='Concluída'",[today]), overdue: await all("SELECT * FROM commercial_daily_tasks WHERE due_date<? AND status!='Concluída'",[today]), hot_leads: await all("SELECT * FROM lead_capture_entries WHERE urgency='Alta' OR temperature='Quente' ORDER BY created_at DESC"), flyer_leads: await all("SELECT * FROM lead_capture_entries WHERE origin='Panfleto' ORDER BY created_at DESC"), social_leads: await all("SELECT * FROM lead_capture_entries WHERE origin IN ('Instagram','TikTok') ORDER BY created_at DESC")});}catch(e){next(e);}});
router.get('/sdr/dashboard', async(req,res,next)=>{try{const today=todayIso(); const leads = await all(`SELECT * FROM lead_capture_entries WHERE ${openStatuses} ORDER BY CASE WHEN next_contact_date<? THEN 0 WHEN next_contact_date=? THEN 1 ELSE 2 END, urgency DESC, created_at ASC`, [today, today]); res.json({today, goal: await goalSummary(), calls_today: leads.filter((l) => !l.next_contact_date || l.next_contact_date <= today), overdue_followups: leads.filter((l) => l.next_contact_date && l.next_contact_date < today), leads, origin_ranking: await all(`SELECT COALESCE(origin,'Sem origem') label, COUNT(*) leads, SUM(CASE WHEN status IN ('Orçamento enviado','Fechado') THEN 1 ELSE 0 END) budgets FROM lead_capture_entries GROUP BY COALESCE(origin,'Sem origem') ORDER BY leads DESC, budgets DESC`), campaign_ranking: await all(`SELECT COALESCE(campaign,'Sem campanha') label, COUNT(*) leads, SUM(CASE WHEN status IN ('Orçamento enviado','Fechado') THEN 1 ELSE 0 END) budgets FROM lead_capture_entries GROUP BY COALESCE(campaign,'Sem campanha') ORDER BY leads DESC, budgets DESC`) });}catch(e){next(e);}});
router.post('/sdr/leads/:id/status', async(req,res,next)=>{try{const statusMap = { contacted: 'Contatado', scheduled: 'Avaliação marcada', budget_sent: 'Orçamento enviado', closed: 'Fechado', lost: 'Perdido' }; const status = statusMap[req.body.action] || req.body.status; if(!status) return res.status(400).json({error:'Ação da SDR inválida.'}); res.json(await updateLeadStatus(req.params.id, status, req.body));}catch(e){next(e);}});
router.post('/commercial-routine/actions', async(req,res,next)=>{try{const b=req.body; const r=await run('INSERT INTO commercial_followup_actions (lead_id,task_id,action_type,channel,message,result,next_contact_date,status) VALUES (?,?,?,?,?,?,?,?)',[b.lead_id,b.task_id,b.action_type,b.channel,b.message,b.result,b.next_contact_date,b.status||'Registrada']); if(b.task_id) await run('UPDATE commercial_daily_tasks SET status=?, updated_at=CURRENT_TIMESTAMP WHERE id=?',[b.task_status||'Concluída',b.task_id]); res.status(201).json(await get('SELECT * FROM commercial_followup_actions WHERE id=?',[r.id]));}catch(e){next(e);}});
router.get('/marketing-daily/dashboard', async(req,res,next)=>{try{const t=todayIso(); res.json({today:t, goal:await goalSummary(), checklist: await all('SELECT * FROM marketing_daily_checklist WHERE checklist_date=? ORDER BY id',[t]), metrics: await get(`SELECT COUNT(*) leads, SUM(CASE WHEN contacted=1 THEN 1 ELSE 0 END) contacted, SUM(CASE WHEN status IN ('Orçamento enviado','Fechado') THEN 1 ELSE 0 END) budgets, SUM(CASE WHEN status='Avaliação marcada' THEN 1 ELSE 0 END) evaluations FROM lead_capture_entries WHERE substr(created_at,1,10)=?`,[t])});}catch(e){next(e);}});
router.get('/marketing-weekly/reports', async(req,res,next)=>{try{const generated = await buildWeeklyReport(); const existing = await all('SELECT * FROM marketing_weekly_reports ORDER BY week_start DESC'); res.json({generated, reports: existing});}catch(e){next(e);}});
router.post('/marketing-weekly/reports/generate', async(req,res,next)=>{try{const report = await buildWeeklyReport(); await run(`INSERT OR IGNORE INTO marketing_weekly_reports (week_start,leads_week,budgets_week,lead_origins,strong_campaigns,weak_campaigns,team_pending,suggested_next_steps) VALUES (?,?,?,?,?,?,?,?)`, [report.week_start,report.leads_week,report.budgets_week,report.lead_origins,report.strong_campaigns,report.weak_campaigns,report.team_pending,report.suggested_next_steps]); await run(`UPDATE marketing_weekly_reports SET leads_week=?, budgets_week=?, lead_origins=?, strong_campaigns=?, weak_campaigns=?, team_pending=?, suggested_next_steps=? WHERE week_start=?`, [report.leads_week,report.budgets_week,report.lead_origins,report.strong_campaigns,report.weak_campaigns,report.team_pending,report.suggested_next_steps,report.week_start]); res.status(201).json(await get('SELECT * FROM marketing_weekly_reports WHERE week_start=?',[report.week_start]));}catch(e){next(e);}});
router.get('/marketing-origin/performance', async(req,res,next)=>{try{res.json(await all(`SELECT COALESCE(origin,'Sem origem') origin, COUNT(*) leads, SUM(CASE WHEN qualification='Qualificado' THEN 1 ELSE 0 END) qualified_leads, SUM(CASE WHEN status IN ('Orçamento enviado','Fechado') THEN 1 ELSE 0 END) budgets FROM lead_capture_entries GROUP BY COALESCE(origin,'Sem origem') ORDER BY leads DESC, budgets DESC`));}catch(e){next(e);}});
router.get('/marketing-alerts', async(req,res,next)=>{try{res.json(await all('SELECT * FROM marketing_campaign_alerts ORDER BY created_at DESC'));}catch(e){next(e);}});
module.exports = router;
