export const groups = [
  { label: 'Hoje', items: [['belleartBrain','BELLEART IA'], ['marketingEmployee','O que fazer hoje'], ['enterprise','Fase Enterprise'], ['enterprise-saas','Enterprise SaaS'], ['premium-os','BELLEART OS Premium'], ['executive','Painel Executivo'], ['notifications','Notificações']] },
  { label: 'Clínica', items: [['clinical','Central Clínica'], ['patients','Pacientes'], ['appointments','Agenda'], ['budgets','Orçamentos'], ['documents','Documentos'], ['implant-crm','CRM de Implantes'], ['referrals','Indicações'], ['reactivation','Reativação']] },
  { label: 'Marketing & Vendas', items: [['enterpriseCrm','CRM Kanban Enterprise'], ['secretary','Secretária Virtual IA'], ['belleartAi','BELLEART AI'], ['marketing','Marketing'], ['lead-capture','Captação de Leads'], ['commercial','Central Comercial'], ['pipeline','Pipeline'], ['leads','Leads'], ['followup','Follow-up'], ['objections','Objeções'], ['crmCampaigns','Campanhas'], ['commercialReports','Relatórios'], ['commercialDashboard','Dashboard Comercial'], ['campaigns','Campanhas Marketing'], ['crm','CRM'], ['whatsapp','WhatsApp Inteligente'], ['tasks','Tarefas Comerciais'], ['captions','Banco de Legendas'], ['content-calendar','Calendário de Conteúdo'], ['ai-assistant','Assistente IA'], ['reels','Roteiros Reels'], ['stories','Banco de Stories'], ['metrics','Métricas Sociais'], ['trafficCenter','Central de Tráfego'], ['trafficCampaigns','Campanhas'], ['trafficPlatforms','Plataformas'], ['trafficLeads','Leads por origem'], ['trafficMetrics','Métricas'], ['trafficRoi','Dashboard ROI'], ['socialIntegrations','Integrações'], ['apiSettings','Configurações de API']] },
  { label: 'MÁQUINA DE MARKETING', items: [['marketingGoals','Meta de Orçamentos'], ['flyers','Panfletagem'], ['quickLead','Entrada Rápida de Lead'], ['commercialRoutine','Central SDR'], ['marketingDaily','Painel Diário'], ['weeklyReport','Relatório Semanal'], ['originPerformance','Desempenho por Origem']] },
  { label: 'Gestão', items: [['financial','Financeiro'], ['automationsEnterprise','Automações Inteligentes'], ['implant-financial','Financeiro de Implantes'], ['reports','Relatórios'], ['automations','Automações']] },
  { label: 'Administração', items: [['backupSecurity','Backup e Segurança'], ['settings','Configurações'], ['backups','Gestão & Backup'], ['users','Usuários'], ['audit','Auditoria'], ['profile','Perfil']] },
];
export const paths = Object.fromEntries(groups.flatMap(g => g.items));
export function allowed(item, user) {
  if (!user) return false; if (user.role === 'administrador' || item === 'profile' || item === 'belleartBrain' || item === 'marketingEmployee' || item === 'enterprise' || item === 'enterprise-saas') return true;
  const map = { dentista:['belleartBrain','marketingEmployee','clinical','patients','appointments','budgets','documents','implant-crm','financial'], recepcao:['belleartBrain','marketingEmployee','secretary','enterpriseCrm','patients','appointments','whatsapp','tasks','notifications','marketing','lead-capture','commercial','pipeline','leads','followup','quickLead','commercialRoutine','marketingDaily'], financeiro:['belleartBrain','marketingEmployee','backupSecurity','premium-os','executive','financial','implant-financial','reports','documents'], marketing:['belleartBrain','marketingEmployee','enterpriseCrm','secretary','belleartAi','automationsEnterprise','premium-os','marketing','lead-capture','commercial','pipeline','leads','followup','objections','crmCampaigns','commercialReports','commercialDashboard','campaigns','crm','whatsapp','captions','content-calendar','ai-assistant','reels','stories','metrics','executive','tasks','marketingGoals','flyers','quickLead','commercialRoutine','marketingDaily','weeklyReport','originPerformance','trafficCenter','trafficCampaigns','trafficPlatforms','trafficLeads','trafficMetrics','trafficRoi','socialIntegrations','apiSettings'], leitura:groups.flatMap(g=>g.items.map(i=>i[0])) };
  return (map[user.role] || []).includes(item);
}
