export const groups = [
  { label: 'Visão Geral', items: [['dashboard','Dashboard'], ['enterprise','Fase Enterprise'], ['enterprise-saas','Enterprise SaaS'], ['premium-os','BELLEART OS Premium'], ['executive','Painel Executivo'], ['notifications','Notificações']] },
  { label: 'Clínica', items: [['patients','Pacientes'], ['appointments','Agenda'], ['budgets','Orçamentos'], ['documents','Documentos'], ['implant-crm','CRM de Implantes'], ['referrals','Indicações'], ['reactivation','Reativação']] },
  { label: 'Marketing & Vendas', items: [['marketing','Marketing'], ['lead-capture','Captação de Leads'], ['commercial','Central Comercial'], ['pipeline','Pipeline'], ['leads','Leads'], ['followup','Follow-up'], ['objections','Objeções'], ['crmCampaigns','Campanhas'], ['commercialReports','Relatórios'], ['commercialDashboard','Dashboard Comercial'], ['campaigns','Campanhas Marketing'], ['crm','CRM'], ['whatsapp','WhatsApp Inteligente'], ['tasks','Tarefas Comerciais'], ['captions','Banco de Legendas'], ['content-calendar','Calendário de Conteúdo'], ['ai-assistant','Assistente IA'], ['reels','Roteiros Reels'], ['stories','Banco de Stories'], ['metrics','Métricas Sociais'], ['trafficCenter','Central de Tráfego'], ['trafficCampaigns','Campanhas'], ['trafficPlatforms','Plataformas'], ['trafficLeads','Leads por origem'], ['trafficMetrics','Métricas'], ['trafficRoi','Dashboard ROI'], ['socialIntegrations','Integrações'], ['apiSettings','Configurações de API']] },
  { label: 'Gestão', items: [['financial','Financeiro'], ['implant-financial','Financeiro de Implantes'], ['reports','Relatórios'], ['automations','Automações']] },
  { label: 'Administração', items: [['settings','Configurações'], ['backups','Gestão & Backup'], ['users','Usuários'], ['audit','Auditoria'], ['profile','Perfil']] },
];
export const paths = Object.fromEntries(groups.flatMap(g => g.items));
export function allowed(item, user) {
  if (!user) return false; if (user.role === 'administrador' || item === 'profile' || item === 'dashboard' || item === 'enterprise' || item === 'enterprise-saas') return true;
  const map = { dentista:['patients','appointments','budgets','documents','implant-crm','financial'], recepcao:['patients','appointments','whatsapp','tasks','notifications','marketing','lead-capture','commercial','pipeline','leads','followup'], financeiro:['premium-os','executive','financial','implant-financial','reports','documents'], marketing:['premium-os','marketing','lead-capture','commercial','pipeline','leads','followup','objections','crmCampaigns','commercialReports','commercialDashboard','campaigns','crm','whatsapp','captions','content-calendar','ai-assistant','reels','stories','metrics','executive','tasks','trafficCenter','trafficCampaigns','trafficPlatforms','trafficLeads','trafficMetrics','trafficRoi','socialIntegrations','apiSettings'], leitura:groups.flatMap(g=>g.items.map(i=>i[0])) };
  return (map[user.role] || []).includes(item);
}
